# Generated by Django 6.0.2 on 2026-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
