# Generated by Django 6.0.2 on 2026-02-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listings_price_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auction_listings',
            new_name='auction_listing',
        ),
        migrations.RenameModel(
            old_name='bids',
            new_name='bid',
        ),
    ]
