# Generated by Django 6.0.2 on 2026-02-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_auction_listings_auction_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
