# Generated by Django 6.0.2 on 2026-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_listing_active_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
