# Generated by Django 6.0.2 on 2026-03-01 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_listing_user_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watched_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
