# Generated by Django 6.0.2 on 2026-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_category_auction_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
