# Generated by Django 6.0.2 on 2026-03-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
