# Generated by Django 6.0.2 on 2026-03-05 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auction_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
