# Generated by Django 6.0.3 on 2026-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
